### ISSUE TITLE
why not English

### ISSUE THREAD

**Issue by KissesJun** [kshjessica/study_Machine-Learning#1]
The repo will look more beautiful if you use English to introduce them.😁

**Comment by kshjessica** [comment]
Thank you for your feedback!

The words in Korean are the subject names and unit names of the classes I took. I had to specify the name to submit the assignment, so it was written in Korean according to a given form.

'생체인증보안' is 'Biometric Security' and '기계학습과인공지능' is 'Machine Learning and Artificial Intelligence' in English.

I hope this information will be of any help:)
